REPO        := $(CURDIR)
CLAUDE_HOME := $(HOME)/.claude
SKILLS      := $(CLAUDE_HOME)/skills
CODEX_HOME  := $(HOME)/.codex
CODEX_SKILLS := $(HOME)/.agents/skills
BACKUP      := $(CLAUDE_HOME)/.repo-sync-backup-$(shell date +%Y%m%d-%H%M%S)

# Claude Code: skills, the agent library, and the statusline are all symlinks.
LINKS := \
	$(SKILLS)/norman:$(REPO)/norman \
	$(SKILLS)/prd:$(REPO)/prd \
	$(SKILLS)/sweep:$(REPO)/sweep \
	$(CLAUDE_HOME)/agents:$(REPO)/agents \
	$(CLAUDE_HOME)/statusline.sh:$(REPO)/statusline/statusline.sh

# Codex: skills are symlinked (Codex follows skill directory links); agents are
# generated into ~/.codex/agents/ as TOML by tools/codex-agents, since Codex
# does not read the markdown format. The global instructions file is shared
# with Claude Code: Codex reads ~/.codex/AGENTS.md where Claude reads
# ~/.claude/CLAUDE.md, and the content is the same set of rules.
CODEX_LINKS := \
	$(CODEX_SKILLS)/norman:$(REPO)/norman \
	$(CODEX_SKILLS)/prd:$(REPO)/prd \
	$(CODEX_SKILLS)/sweep:$(REPO)/sweep \
	$(CODEX_HOME)/AGENTS.md:$(CLAUDE_HOME)/CLAUDE.md

.PHONY: install uninstall status install-codex uninstall-codex status-codex test help

help:
	@echo "Claude Code targets:"
	@echo "  install          Symlink skills/agents/statusline from this repo into ~/.claude/"
	@echo "                   (backs up existing real files/dirs to a timestamped folder)"
	@echo "  uninstall        Remove symlinks that point into this repo (leaves backups)"
	@echo "  status           Show current link state of each managed path"
	@echo "Codex targets:"
	@echo "  install-codex    Symlink skills into ~/.agents/skills/ and generate ~/.codex/agents/*.toml"
	@echo "  uninstall-codex  Remove the skill symlinks and generated agent TOML files"
	@echo "  status-codex     Show link state and generated agent count"
	@echo "Other:"
	@echo "  test             Run the Go tests for tools/"

# $(call link-pairs,<dest:src pairs>)
define link-pairs
	for pair in $(1); do \
		dest=$${pair%%:*}; src=$${pair##*:}; \
		mkdir -p "$$(dirname "$$dest")"; \
		if [ -L "$$dest" ]; then \
			if [ "$$(readlink "$$dest")" = "$$src" ]; then \
				echo "[skip] $$dest -> already linked"; \
				continue; \
			fi; \
			echo "[relink] $$dest -> $$src"; \
			rm "$$dest"; \
		elif [ -e "$$dest" ]; then \
			mkdir -p "$(BACKUP)"; \
			echo "[backup] $$dest -> $(BACKUP)/"; \
			mv "$$dest" "$(BACKUP)/" || exit 1; \
			echo "[link]   $$dest -> $$src"; \
		else \
			echo "[link]   $$dest -> $$src"; \
		fi; \
		ln -s "$$src" "$$dest" || exit 1; \
	done
endef

# $(call unlink-pairs,<dest:src pairs>)
define unlink-pairs
	for pair in $(1); do \
		dest=$${pair%%:*}; src=$${pair##*:}; \
		if [ -L "$$dest" ] && [ "$$(readlink "$$dest")" = "$$src" ]; then \
			rm "$$dest"; echo "[unlink] $$dest"; \
		else \
			echo "[skip]   $$dest (not a symlink into this repo)"; \
		fi; \
	done
endef

# $(call status-pairs,<dest:src pairs>)
define status-pairs
	for pair in $(1); do \
		dest=$${pair%%:*}; src=$${pair##*:}; \
		if [ -L "$$dest" ]; then \
			target=$$(readlink "$$dest"); \
			if [ "$$target" = "$$src" ]; then \
				echo "[ok]   $$dest -> $$target"; \
			else \
				echo "[warn] $$dest -> $$target (expected $$src)"; \
			fi; \
		elif [ -e "$$dest" ]; then \
			echo "[real] $$dest (not a symlink)"; \
		else \
			echo "[miss] $$dest"; \
		fi; \
	done
endef

install:
	@$(call link-pairs,$(LINKS))
	@echo "Done. Run 'make status' to verify."

uninstall:
	@$(call unlink-pairs,$(LINKS))

status:
	@$(call status-pairs,$(LINKS))

install-codex:
	@$(call link-pairs,$(CODEX_LINKS))
	@cd tools/codex-agents && go run . -src "$(REPO)/agents" -out "$(CODEX_HOME)/agents"
	@echo "Done. Run 'make status-codex' to verify."

uninstall-codex:
	@$(call unlink-pairs,$(CODEX_LINKS))
	@cd tools/codex-agents && go run . -out "$(CODEX_HOME)/agents" -uninstall

status-codex:
	@$(call status-pairs,$(CODEX_LINKS))
	@n=$$(grep -ls '^# generated by norman' "$(CODEX_HOME)"/agents/*.toml 2>/dev/null | wc -l); \
		echo "[info] $$n generated agents in $(CODEX_HOME)/agents/"

test:
	@cd tools/codex-agents && go test ./...
