package main

import (
	"errors"
	"fmt"
	"strings"
)

// Agent is one Claude Code agent definition: the YAML frontmatter fields
// norman cares about plus the system prompt that follows it.
type Agent struct {
	Name        string
	Description string
	Model       string
	Body        string
}

// generatedMarker is the first line of every TOML file this tool writes.
// Uninstall removes only files that start with it, so hand-written agents
// in the same directory are never touched.
const generatedMarker = "# generated by norman (tools/codex-agents) - do not edit, regenerate with `make install-codex`"

// parseAgent splits an agent markdown file into frontmatter fields and body.
// Only single-line `key: value` frontmatter is supported, which is all the
// agents/ library uses.
func parseAgent(src []byte) (Agent, error) {
	s := strings.ReplaceAll(string(src), "\r\n", "\n")
	if !strings.HasPrefix(s, "---\n") {
		return Agent{}, errors.New("missing frontmatter")
	}
	rest := s[len("---\n"):]
	end := strings.Index(rest, "\n---\n")
	if end < 0 {
		return Agent{}, errors.New("unterminated frontmatter")
	}
	a := Agent{Body: strings.TrimSpace(rest[end+len("\n---\n"):])}
	for _, line := range strings.Split(rest[:end], "\n") {
		k, v, ok := strings.Cut(line, ":")
		if !ok {
			continue
		}
		v = strings.TrimSpace(v)
		if len(v) >= 2 && v[0] == '"' && v[len(v)-1] == '"' {
			v = v[1 : len(v)-1]
		}
		switch strings.TrimSpace(k) {
		case "name":
			a.Name = v
		case "description":
			a.Description = v
		case "model":
			a.Model = v
		}
	}
	if a.Name == "" {
		return Agent{}, errors.New("frontmatter has no name")
	}
	if a.Description == "" {
		return Agent{}, errors.New("frontmatter has no description")
	}
	if a.Body == "" {
		return Agent{}, errors.New("empty body")
	}
	return a, nil
}

// toTOML renders an Agent as a Codex custom agent file. `model: inherit`
// (or no model) omits the key so Codex inherits the parent's model, which
// is what norman relies on when it picks the tier at spawn time. Any other
// model value is passed through unchanged; the caller decides whether to
// warn about it.
func toTOML(a Agent) string {
	var b strings.Builder
	b.WriteString(generatedMarker)
	b.WriteString("\n")
	fmt.Fprintf(&b, "name = %s\n", tomlBasic(a.Name))
	fmt.Fprintf(&b, "description = %s\n", tomlBasic(a.Description))
	if a.Model != "" && a.Model != "inherit" {
		fmt.Fprintf(&b, "model = %s\n", tomlBasic(a.Model))
	}
	b.WriteString("sandbox_mode = \"workspace-write\"\n")
	b.WriteString("developer_instructions = \"\"\"\n")
	b.WriteString(tomlMultiline(a.Body))
	b.WriteString("\n\"\"\"\n")
	return b.String()
}

// tomlBasic quotes s as a single-line TOML basic string.
func tomlBasic(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\t", `\t`, "\r", `\r`)
	return `"` + r.Replace(s) + `"`
}

// tomlMultiline escapes s for the inside of a TOML multi-line basic string.
// Newlines and tabs are legal as-is; backslashes and any run of three
// quotes must be escaped or they terminate the string early.
func tomlMultiline(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"""`, `""\"`)
	return s
}
