// Command codex-agents converts the agents/ library (Claude Code markdown
// agents) into Codex CLI custom agent TOML files.
//
//	codex-agents -src agents -out ~/.codex/agents
//	codex-agents -out ~/.codex/agents -uninstall
//
// Install writes one <name>.toml per agent. Uninstall removes only files
// that carry the generated marker on their first line.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	src := flag.String("src", "agents", "directory of Claude Code agent markdown files")
	out := flag.String("out", "", "directory to write Codex agent TOML files into (required)")
	uninstall := flag.Bool("uninstall", false, "remove generated TOML files from -out instead of writing them")
	flag.Parse()

	if *out == "" {
		fmt.Fprintln(os.Stderr, "codex-agents: -out is required")
		os.Exit(2)
	}
	var err error
	if *uninstall {
		err = uninstallDir(*out, os.Stdout)
	} else {
		err = installDir(*src, *out, os.Stdout, os.Stderr)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "codex-agents:", err)
		os.Exit(1)
	}
}

// installDir converts every *.md agent in src into out/<name>.toml and
// removes generated TOML whose source agent no longer exists, so deleting
// an agent from the library also retires it from Codex on the next install.
// Files without frontmatter (README.md) are skipped with a note.
func installDir(src, out string, log, warn *os.File) error {
	entries, err := filepath.Glob(filepath.Join(src, "*.md"))
	if err != nil {
		return err
	}
	if len(entries) == 0 {
		return fmt.Errorf("no agent files in %s", src)
	}
	if err := os.MkdirAll(out, 0o750); err != nil {
		return err
	}
	written := 0
	fresh := map[string]bool{}
	for _, path := range entries {
		raw, err := os.ReadFile(filepath.Clean(path)) // #nosec G304 -- path comes from globbing the operator-supplied -src directory
		if err != nil {
			return err
		}
		a, err := parseAgent(raw)
		if err != nil {
			fmt.Fprintf(log, "[skip]  %s (%v)\n", path, err)
			continue
		}
		if a.Model != "" && a.Model != "inherit" {
			fmt.Fprintf(warn, "[warn]  %s: model %q is passed through verbatim; Codex may not know it\n", path, a.Model)
		}
		dest := filepath.Join(out, a.Name+".toml")
		if err := os.WriteFile(dest, []byte(toTOML(a)), 0o600); err != nil {
			return err
		}
		fmt.Fprintf(log, "[write] %s\n", dest)
		fresh[dest] = true
		written++
	}
	pruned, err := pruneOrphans(out, fresh, log)
	if err != nil {
		return err
	}
	fmt.Fprintf(log, "Done. %d agents written to %s, %d orphaned removed\n", written, out, pruned)
	return nil
}

// pruneOrphans removes generated TOML files in dir that this run did not
// write. Hand-written files (no marker) are never touched.
func pruneOrphans(dir string, fresh map[string]bool, log *os.File) (int, error) {
	entries, err := filepath.Glob(filepath.Join(dir, "*.toml"))
	if err != nil {
		return 0, err
	}
	pruned := 0
	for _, path := range entries {
		if fresh[path] {
			continue
		}
		gen, err := isGenerated(path)
		if err != nil {
			return pruned, err
		}
		if !gen {
			continue
		}
		if err := os.Remove(path); err != nil {
			return pruned, err
		}
		fmt.Fprintf(log, "[prune] %s (source agent no longer exists)\n", path)
		pruned++
	}
	return pruned, nil
}

// uninstallDir removes every *.toml in dir whose first line is the
// generated marker, leaving hand-written agents alone.
func uninstallDir(dir string, log *os.File) error {
	entries, err := filepath.Glob(filepath.Join(dir, "*.toml"))
	if err != nil {
		return err
	}
	removed := 0
	for _, path := range entries {
		gen, err := isGenerated(path)
		if err != nil {
			return err
		}
		if !gen {
			fmt.Fprintf(log, "[keep]   %s (not generated by norman)\n", path)
			continue
		}
		if err := os.Remove(path); err != nil {
			return err
		}
		fmt.Fprintf(log, "[remove] %s\n", path)
		removed++
	}
	fmt.Fprintf(log, "Done. %d generated agents removed from %s\n", removed, dir)
	return nil
}

func isGenerated(path string) (bool, error) {
	f, err := os.Open(filepath.Clean(path)) // #nosec G304 -- path comes from globbing the operator-supplied -out directory
	if err != nil {
		return false, err
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	if !sc.Scan() {
		return false, sc.Err()
	}
	return strings.TrimSpace(sc.Text()) == generatedMarker, nil
}
